### ISSUE TITLE
[bug]: `/song keyword` コマンド発火時にデータ取得に失敗している

### ISSUE THREAD

**Issue by hizumiaoba** [Secret-Society-Braid/MochiMochiTalk#148]
### 発生した不具合

`/song keyword` コマンドを送信時、値が返却されず、検索開始後のプレースホルダテキストから遷移しない

以下ログファイルからのエラー部分抜粋

```bash
2023-11-19 10:34:34,228 INFO [JDA MainWS-ReadThread] M.c.CommandSong [CommandSong.java : 192] got interaction with following command: keyword in song
2023-11-19 10:34:34,233 DEBUG [JDA MainWS-ReadThread] h.i.b.ListEndPointBuilder [ListEndPointBuilder.java : 192] set parameters: {search=Fashionable, music_type=cg, limit=1, type=music}
2023-11-19 10:34:34,233 INFO [JDA MainWS-ReadThread] h.i.b.ListEndPointBuilder [ListEndPointBuilder.java : 193] constructing action instance...
2023-11-19 10:34:34,233 DEBUG [JDA MainWS-ReadThread] h.u.CountingThreadFactory [CountingThreadFactory.java : 19] Initiate Single Thread Factory.
2023-11-19 10:34:34,234 DEBUG [JDA MainWS-ReadThread] h.u.CountingThreadFactory [CountingThreadFactory.java : 20] The Thread name is Rest action handshaking thread
2023-11-19 10:34:34,235 DEBUG [JDA MainWS-ReadThread] h.i.b.ListEndPointBuilder [ListEndPointBuilder.java : 196] complete. information: hajimeapi4j.internal.request.RestActionImpl@7c4e4dc8
2023-11-19 10:34:34,241 INFO [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 22] api requester has been created
2023-11-19 10:34:34,245 INFO [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 34] opening connection with following data
2023-11-19 10:34:34,245 INFO [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 35] Route data: hajimeapi4j.internal.request.CompiledRoute@4d034ed8
2023-11-19 10:34:34,245 INFO [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 36] Request method: GET
2023-11-19 10:34:34,245 INFO [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 37] User Agent: HajimeAPI4J java wrapper developed by @hizumiaoba
2023-11-19 10:34:34,245 INFO [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 38] API Version: v2
2023-11-19 10:34:34,661 DEBUG [JDA RateLimit-Worker 5] n.d.j.i.r.Requester [Requester.java : 224] Received response with following cf-rays: [8287cd1e98d580b1-NRT]
2023-11-19 10:34:34,825 DEBUG [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 41] used input stream instance data: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@5f3490f2
2023-11-19 10:34:34,826 DEBUG [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 42] received properties: {null=[HTTP/1.1 200 OK], Server=[nginx], Access-Control-Allow-Origin=[*], Content-Location=[list.php], Connection=[keep-alive], Set-Cookie=[ENC__mw-wp-form-token=hRb7hR9iHtQZZygQHIuYYL90LvxpeTEbYGqHEQcq76sWBbtkjL0vbn4tqci2LMsnYhewOePQimKifSJI/t8SOrpu6eyXvaHUv9Tvtk3Qarvs8y7MxxGtj2LX%2b4DnIVSu; path=/; secure; HttpOnly], Vary=[negotiate], Content-Length=[4], TCN=[choice], Date=[Sun, 19 Nov 2023 10:34:32 GMT], X-Powered-By=[FH-API/v1], Content-Type=[application/json; charset=utf-8]}
2023-11-19 10:34:34,826 DEBUG [Rest action handshaking thread-worker 1] h.i.r.Requester [Requester.java : 43] latest modified at: 0
2023-11-19 10:34:34,830 DEBUG [Rest action handshaking thread-worker 1] h.u.ParseUtil [ParseUtil.java : 38] attempt to parse list data
2023-11-19 10:34:34,863 DEBUG [Rest action handshaking thread-worker 1] h.u.ParseUtil [ParseUtil.java : 43] Parsing completed. took 33 ms
2023-11-19 10:34:34,863 DEBUG [Rest action handshaking thread-worker 1] h.u.ParseUtil [ParseUtil.java : 44] generated data: null
2023-11-19 10:34:34,865 WARN [MochiMochiTalk Song detail integration thread-Worker 2] M.u.ConcurrencyUtil [ConcurrencyUtil.java : 21] There was an error while handling an event. ret=null, t={}
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "response" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1313)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "response" is null
	at MochiMochiTalk.commands.CommandSong.createSearchResultMessage(CommandSong.java:138)
	at MochiMochiTalk.commands.CommandSong.lambda$invokeKeyword$7(CommandSong.java:102)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	... 5 common frames omitted
2023-11-19 10:34:38,112 DEBUG [JDA RateLimit-Worker 2] n.d.j.a.r.RestRateLimiter [SequentialRestRateLimiter.java : 199] Removed 1 expired buckets
```

### 期待した挙動

正常に曲検索が行われる

### 推定される発生時刻

2023-11-19

**Comment by hizumiaoba** [comment]
検索結果が0である場合の可能性？
もしそうであれば候補なし修正として別チケットを作成予定

**Comment by hizumiaoba** [comment]
ふじわらはじめAPI さん側に報告を送っているので応答待ち

**Comment by hizumiaoba** [comment]
> ふじわらはじめAPI さん側に報告を送っているので応答待ち

API側で対処済み、ラッパークラスに問題があるようなので対処

**Comment by hizumiaoba** [comment]
Secret-Society-Braid/HajimeAPI4J#121 の解決待ち
