### ISSUE TITLE
[bug]: メッセージイベント受信とコマンド処理が重なった場合の挙動

### ISSUE THREAD

**Issue by hizumiaoba** [Secret-Society-Braid/MochiMochiTalk#24]
### 発生した不具合

イベント処理が複数重なり、処理が重くなった

以下ログ
```log
15:10:05.447 [JDA MainWS-ReadThread] INFO  M.voice.nvoice.EventListenerForTTS - User wants Bot to be connected. connecting...
15:10:05.447 [JDA MainWS-ReadThread] INFO  M.voice.nvoice.EventListenerForTTS - Requested guild: Guild:むつコード(id=629249258960453652)
15:10:05.449 [JDA MainWS-ReadThread] INFO  M.commands.CommandWhatsNew - reading whats new from the description file...
15:10:05.449 [JDA MainWS-ReadThread] INFO  M.commands.CommandWhatsNew - description file name is description.json
15:10:05.450 [JDA MainWS-ReadThread] INFO  M.commands.CommandWhatsNew - description file read completed
15:10:05.451 [JDA MainWS-ReadThread] INFO  M.voice.nvoice.EventListenerForTTS - Connected to the voice channel.
15:10:05.616 [JDA MainWS-ReadThread] INFO  M.voice.nvoice.EventListenerForTTS - Analyzing message: もちもーちで召喚された？
15:10:05.617 [JDA MainWS-ReadThread] INFO  M.voice.nvoice.EventListenerForTTS - Channel: フリーチャット
15:10:05.617 [JDA MainWS-ReadThread] INFO  M.voice.nvoice.EventListenerForTTS - Author: みけまる
15:10:05.617 [JDA MainWS-ReadThread] INFO  M.voice.nvoice.EventListenerForTTS - Guild: むつコード
15:10:05.850 [JDA RateLimit-Worker 3] DEBUG n.d.jda.internal.requests.Requester - Received response with following cf-rays: [7776e7c4a86480e3-NRT]
15:10:05.851 [ForkJoinPool.commonPool-worker-2] ERROR n.d.jda.api.requests.RestAction - RestAction queue returned failure
net.dv8tion.jda.api.exceptions.ErrorResponseException: 10062: Unknown interaction
        at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:185)
        at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:139)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:284)
        at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.handleResponse(InteractionCallbackImpl.java:109)
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:282)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:219)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:143)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:126)
        at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:481)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:73)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:200)
        at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:74)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
        at MochiMochiTalk.voice.nvoice.EventListenerForTTS.onConnectWithSlash(EventListenerForTTS.java:271)
        at MochiMochiTalk.voice.nvoice.EventListenerForTTS.onSlashCommandInteraction(EventListenerForTTS.java:138)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:424)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:171)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:112)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:984)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:870)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:848)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1023)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

### 期待した挙動

正常にイベントを処理する

### 推定される発生時刻

2022-12-11 0:10頃

**Comment by hizumiaoba** [comment]
#60 にて（一応）解消
今後の状況によってはre-openする可能性あり
